<?
$arTooltips = array(
	"IBLOCK_TYPE" => GetMessage("IBLOCK_TYPE_TIP"),
	"IBLOCK_ID" => GetMessage("IBLOCK_ID_TIP"),
	"SORT_BY1" => GetMessage("SORT_BY1_TIP"),
	"SORT_ORDER1" => GetMessage("SORT_ORDER1_TIP"),
	"SORT_BY2" => GetMessage("SORT_BY2_TIP"),
	"SORT_ORDER2" => GetMessage("SORT_ORDER2_TIP"),
	"FILTER_NAME" => GetMessage("FILTER_NAME_TIP"),
	"DETAIL_URL" => GetMessage("DETAIL_URL_TIP"),
	"CACHE_TYPE" => GetMessage("CACHE_TYPE_TIP"),
	"CACHE_TIME" => GetMessage("CACHE_TIME_TIP"),
	"PARENT_SECTION" => GetMessage("PARENT_SECTION_TIP"),
	"AJAX_MODE" => GetMessage("AJAX_MODE_TIP"),
	"AJAX_OPTION_SHADOW" => GetMessage("AJAX_OPTION_SHADOW_TIP"),
	"AJAX_OPTION_JUMP" => GetMessage("AJAX_OPTION_JUMP_TIP"),
	"AJAX_OPTION_STYLE" => GetMessage("AJAX_OPTION_STYLE_TIP"),
	"AJAX_OPTION_HISTORY" => GetMessage("AJAX_OPTION_HISTORY_TIP"),
	"CHECK_DATES" => GetMessage("CHECK_DATES_TIP"),
);
?>