<?php

$s_meta_array= array(
    "/catalog/stroitelnaya-tekhnika/filter/brand-john_deere/" => array("h1" => "John Deere (Джон Дир) строительная техника", "title" => "John Deere (Джон Дир)  строительная техника", "keywords" => "Строительная техника, John Deere, Джон Дир", "description" => "Строительная техника от John Deere (Джон Дир) - одного из ведущих производителей дорожно-строительной техники", "seosmall" => "Марка John Deere (Джон Дир) ассоциируется во всем мире с такими понятиями как надежность и долговечность. Приобретая эту технику, вы можете быть уверены в том, что она техника прослужит долго и качественно."),
    "/catalog/stroitelnaya-tekhnika/filter/brand-manitou/" => array("h1" => "Manitou (Маниту) подъемники и погрузчики", "title" => "Manitou (Маниту) подъемники и погрузчики", "keywords" => "Подъемники, погрузчики, Manitou, Маниту", "description" => "Manitou (Маниту) - подъемники, коленчатые подъемники, ножничные подъемники, телескопические погрузчики от официального дилера Manitou в России"),
    "/catalog/mobilnye-krany/filter/brand-grove/" => array("h1" => "Grove (Грове) краны", "title" => "Краны Grove (Грове)", "keywords" => "Краны, Grove, Грове", "description" => "Краны Grove (Грове) - самоходные краны, короткобазные краны от официального дилера Grove в России"),
    "/catalog/stroitelnaya-tekhnika/filter/brand-ammann/" => array("h1" => "Ammann (Амманн) катки и другая техника", "title" => "Катки и другая техника  Ammann, Амманн", "keywords" => "Строительная техника, Катки, Ammann, Амманн", "description" => "Катки Ammann (Амманн) - асфальтоукладчики, катки, виброплиты, вибротрамбовки от официального дилера Ammann в России. Высокая надежность, низкие эксплуатационные расходы, максимальная производительность - основные качества Ammann"),
    "/catalog/stroitelnaya-tekhnika/filter/brand-yanmar/" => array("h1" => "YANMAR (Янмар) экскаваторы", "title" => "Экскаваторы YANMAR, Янмар", "keywords" => "Экскаваторы, YANMAR, Янмар", "description" => "Экскаваторы YANMAR (Янмар) - мини-экскаваторы от официального дилера YANMAR в России.  Мини-экскаваторы  массой от 0,5 до 10 тонн. Марка YANMAR занимает лидирующие позиции на рынке мини-техники в Европе. "),
    "/catalog/mobilnye-krany/filter/brand-manitowoc/" => array("h1" => "Manitowoc (Манитовок) краны", "title" => "Manitowoc (Манитовок) краны", "keywords" => "Краны , Manitowoc, Манитовок", "description" => "Manitowoc (Манитовок)  краны от официального дилера Manitowoc в России. Компания Manitowoc неизменно занимает лидирующие позиции на рынке производства мобильных кранов"),
    "/catalog/stroitelnaya-tekhnika/filter/brand-morooka/" => array("h1" => "Строительная техника Morooka (Морука)", "title" => "Строительная техника Morooka (Морука)", "keywords" => "Строительная техника, Morooka, Морука", "description" => "Строительная техника Morooka (Морука) от официального дилера Manitowoc в России. Morooka – всемирно признанный брэнд - мировой лидер в категории гусеничные самосвалы, которые используются для выполнения самых разнообразных задач."),
    "/catalog/katki/filter/tip_mashiny-gruntovyy/" => array("h1" => "Грунтовые катки", "title" => "Грунтовые катки купить", "keywords" => "Грунтовые катки, грунтовый, каток, ammann", "description" => "Грунтовые катки AMMANN обеспечивают максимальную производительность даже в самых сложных условиях работы. "),
    "/catalog/katki/filter/tip_mashiny-kombinirovannyy/" => array("h1" => "Каток комбинированный", "title" => "Комбинированные катки купить", "keywords" => "Комбинированные катки", "description" => "Большой выбор комбинированных катков в наличии и под заказ от официального дилера в России. Область применения комбинированного катка - как приавило, для  уплотнения асфальтового полотна"),
    "/catalog/katki/filter/tip_mashiny-pnevmoshinnyy/" => array("h1" => "Пневмошинные катки", "title" => "Пневмошинные катки купить", "keywords" => "Пневмошинный, каток", "description" => "Пневмошинные катки от официального дилера. Ammann - один из ведущих производителей катков в мире. Их максимальная производительность, безопасность, а также простота в использовании являются основными качествами всей продукции компании AMMANN."),
    "/catalog/katki/filter/tip_mashiny-tandem_sharnirno_sochlenennyy/" => array("h1" => "Каток тандемный с шарнирно-сочлененной рамой", "title" => "Каток тандемный с шарнирно-сочлененной рамой", "keywords" => "Тандемный, каток, с шарнирно-сочлененной рамой", "description" => "Тандемные катки с шарнирно-сочлененной рамой. Тандемные катки Ammann были разработаны для дорожно-строительных проектов по всему миру, для уплотнения асфальтовых подслоев, а также гравия и грунта."),
    "/catalog/teleskopicheskie-pogruzchiki/filter/tip_mashiny-povyshennoy_gruzopodemnosti/" => array("h1" => "Погрузчики грузоподъемные", "title" => "Погрузчики грузоподъемны купитье", "keywords" => "Погрузчики, грузоподъемные", "description" => "Погрузчики повышенной грузоподъемности от официального дилера Manitou (Маниту)"),
    "/catalog/teleskopicheskie-pogruzchiki/filter/tip_mashiny-s_nepovorotnoy_bashney/" => array("h1" => "Погрузчики с неповоротной башней", "title" => "Погрузчики с неповоротной башней", "keywords" => "Погрузчики, с неповоротной башней", "description" => "Погрузчики с неповоротной башней от официального дилера Manitou (Маниту)"),
    "/catalog/teleskopicheskie-pogruzchiki/filter/tip_mashiny-s_povorotnoy_bashney/" => array("h1" => "Погрузчики поворотные", "title" => "Погрузчики поворотные купить", "keywords" => "Погрузчики с поворотной башней, Погрузчики поворотные", "description" => "Погрузчики с поворотной башней от официального дилера Manitou (Маниту)"),
    "/catalog/podemniki/filter/tip_mashiny-vertikalnyy/" => array("h1" => "Подъемники вертикальные", "title" => "Подъемники вертикальные", "keywords" => "Подъемники, вертикальные купить", "description" => "Подъемники вертикальные от французского производителя Manitou (Маниту)"),
    "/catalog/podemniki/filter/tip_mashiny-kolenchatyy/" => array("h1" => "Подъемники коленчатые", "title" => "Подъемники коленчатые", "keywords" => "Подъемники, коленчатые купить", "description" => "Подъемники коленчатые от французского производителя Manitou (Маниту)"),
    "/catalog/podemniki/filter/tip_mashiny-nozhnichnyy/" => array("h1" => "Подъемники ножничные", "title" => "Подъемники ножничные", "keywords" => "Подъемник ножничный купить", "description" => "Подъемники ножничные от французского производителя Manitou (Маниту)"),
    "/catalog/skladskaya-tekhnika/filter/brand-yale/" => array("h1" => "Yale (Йел)", "title" => "Yale (Йел)", "keywords" => "Складская техника, Yale, Йел", "description" => "Yale (Йел) складская техника от официального дилера. Бренд складской техники Yale  входит в тройку мировых лидеров по объему продаж подъемно-транспортного оборудования."),
    "/catalog/skladskaya-tekhnika/filter/brand-combilift/" => array("h1" => "Combilift (Комбилифт)", "title" => "Combilift (Комбилифт)", "keywords" => "Складская техника, Combilift, Комбилифт", "description" => "Combilift (Комбилифт)  складская техника от официального дилера. Погрузчики, обработчики контейнеров от известного производителя Combilift."),
    "/catalog/skladskaya-tekhnika/filter/brand-aisle_master/" => array("h1" => "Aisle-Master", "title" => "Aisle-Master ", "keywords" => "Складская техника, Aisle-Master", "description" => "Складская техника Aisle-Master"),
    "/catalog/skladskaya-tekhnika/filter/brand-unilift/" => array("h1" => "UniLift (Юнилифт) тележки, штабелеры", "title" => "UniLift (Юнилифт)  тележки, штабелеры", "keywords" => " тележки, штабелеры, UniLift (Юнилифт)", "description" => "UniLift (Юнилифт)  складская техника и тележки от официального дилера. Грузовая техника -  ручные штабелеры, электрические штабелеры и погрузчики грузоподъемностью от 500 кг до 5000 кг от UniLift"),
    "/catalog/skladskaya-tekhnika/filter/brand-utilev/" => array("h1" => "UTILEV Складская техника", "title" => "UTILEV Складская техника", "keywords" => "Складская техника, UTILEV", "description" => "Складская техника UTILEV от официального дилера. Погрузчики UTILEV от ведущего мирового производителя подъемно-транспортного оборудования"),
    "/catalog/vilochnye-pogruzchiki/filter/brand-yale/" => array("h1" => "Вилочные погрузчики Yale", "title" => "Вилочные погрузчики Yale купить", "keywords" => "Вилочные погрузчики, автопогрузчики, Yale, Йел, Яле", "description" => "Вилочные погрузчики Yale - большой выбор, погрузчики Yale в наличии"),
    "/catalog/vilochnye-pogruzchiki/filter/brand-yale/pto_tip_privoda-elektricheskiy/" => array("h1" => "Электропогрузчики Yale", "title" => "Электропогрузчики Yale купить", "keywords" => "Вилочные, электропогрузчики, Yale, Йел, Яле", "description" => "Вилочные электропогрузчики Yale - большой выбор, электропогрузчики Yale в наличии"),
    "/catalog/vilochnye-pogruzchiki/filter/brand-utilev/" => array("h1" => "Погрузчики UTILEV", "title" => "Погрузчики UTILEV купить", "keywords" => "Вилочные погрузчики, автопогрузчики, UTILEV", "description" => "Вилочные погрузчики UTILEV  от официального дилера. Дизельные автопогрузчиик, газ-бензиновые автопогрузчики в доставкой в любой регион России."),
    
    "/catalog/vilochnye-pogruzchiki/filter/pto_tip_privoda-dizel/" => array("h1" => "Вилочные погрузчики дизельные", "title" => "Вилочные погрузчики дизельные купить", "keywords" => "Вилочные погрузчики, дизельные погрузчики, автопогрузчик дизельный", "description" => "Вилочные погрузчики дизельные - большой выбор. Дизельные погрузчики с доставкой по всей России. Гарантия. ", "seosmall" => "Дизельные погрузчики - идеальное решение для складов. У нас вы можете купить не только дизель погрузчики со склада в Москве, а также заказать другие модели через наших менеджеров."),
    "/catalog/vilochnye-pogruzchiki/filter/pto_tip_privoda-gaz/" => array("h1" => "Погрузчики газовые", "title" => "Погрузчики газовые купить", "keywords" => "Вилочные погрузчики, газовые, на газу", "description" => "Вилочные погрузчики газовые"),
    "/catalog/vilochnye-pogruzchiki/filter/pto_tip_privoda-gaz_benzin/" => array("h1" => "Погрузчики бензиновые ", "title" => "Погрузчик  бензиновый купить", "keywords" => "вилочный погрузчик,  бензиновый", "description" => "Вилочные погрузчики газ/бензин от официального дилера. Производители -  Yale,  UTILEV"),
    "/catalog/vilochnye-pogruzchiki/filter/pto_tip_privoda-elektricheskiy/" => array("h1" => "Погрузчики электрические", "title" => "Погрузчики электрические купить", "keywords" => "Вилочные погрузчики, электрические", "description" => "Электропогрузчики - широкий выбор, в наличии и под заказ. Вилочные погрузчики электрические от известного произвдителя Yale"),
    "/catalog/gidravlicheskie-telezhki/filter/brand-yale/" => array("h1" => "Yale (Йел) тележки", "title" => "Yale (Йел) тележки купить", "keywords" => "Гидравлические тележки, Yale, Йел, Яле, купить", "description" => "Гидравлические тележки Yale (Йел) от официального дилера."),
    "/catalog/gidravlicheskie-telezhki/filter/brand-unilift/" => array("h1" => "UniLift (Юнилифт) тележки", "title" => "UniLift (Юнилифт) тележки купить", "keywords" => "Гидравлические тележки, UniLift, Юнилифт, купить", "description" => "Гидравлические тележки UniLift (Юнилифт)  от официального дилера."),
    "/catalog/mnogokhodovye-pogruzchiki/filter/pto_tip_privoda-gazovyy/" => array("h1" => "Боковые погрузчики газовые", "title" => "Боковые погрузчики газовые купить", "keywords" => "Боковые погрузчики газовые, купить", "description" => "Боковые погрузчики газовые. Многоходовые погрузчики на газу от официального дилера."),
    "/catalog/mnogokhodovye-pogruzchiki/filter/pto_tip_privoda-dizelnyy/" => array("h1" => "Боковые погрузчики дизельные", "title" => "Боковые погрузчики дизельные купить", "keywords" => "Боковые погрузчики дизельные, купить", "description" => "Боковые погрузчики дизельные. Многоходовые погрузчики на дизеле от официального дилера."),
    "/catalog/mnogokhodovye-pogruzchiki/filter/pto_tip_privoda-elektricheskiy/" => array("h1" => "Боковые погрузчики электрические", "title" => "Боковые погрузчики электрические купить", "keywords" => "Боковые погрузчики электрические, купить", "description" => "Боковые погрузчики электрические.  Многоходовые электропогрузчики от официального дилера."),
    "/catalog/elektricheskie-shtabelery/filter/brand-yale/" => array("h1" => "Электроштабелеры Yale (Йел)", "title" => "Электроштабелеры Yale (Йел) купить", "keywords" => "Электроштабелеры, Yale, Йел, Ял, купитье", "description" => "Электроштабелеры Yale (Йел) от официального дилера. Электрические штабелеры Yale с доставкой в любой регион России."),
    "/catalog/elektricheskie-shtabelery/filter/brand-unilift/" => array("h1" => "Электроштабелеры UniLift (Юнилифт)", "title" => "Электроштабелеры UniLift (Юнилифт) купить", "keywords" => "Электроштабелеры, UniLift, Юнилифт, купить", "description" => "Электроштабелеры UniLift (Юнилифт) от официального дилера.  Электрические штабелеры с доставкой в любой регион России."),
    "/catalog/elektricheskie-shtabelery/filter/pto_tip_privoda-poluelektricheskiy/" => array("h1" => "Штабелеры полуэлектрические", "title" => "Штабелеры полуэлектрические купить", "keywords" => "Штабелер полуэлектрический, купить", "description" => "Штабелер полуэлектрический от официального дилера."),
    "/catalog/elektricheskie-shtabelery/filter/pto_tip_privoda-elektricheskiy/" => array("h1" => "Штабелеры электрические", "title" => "Штабелеры электрические купить", "keywords" => "Штабелер электрический, купить", "description" => "Штабелер электрический от официального дилера."),
    "/catalog/generatory/filter/brand-sdmo/" => array("h1" => "Генераторы SDMO (СДМО)", "title" => "Генераторы SDMO (СДМО) купить", "keywords" => "Генераторы, SDMO, СДМО, купить", "description" => "Генераторы SDMO (СДМО) - большой выбор.  От официального дилера."),
    "/catalog/dizelnye-generatory/filter/brand-sdmo/" => array("h1" => "Дизель генераторы SDMO (СДМО)", "title" => "Дизель генераторы SDMO (СДМО) купить", "keywords" => "Дизельные генераторы, SDMO, СДМО, купить", "description" => "Дизель генераторы марки SDMO (СДМО) - большой выбор. Дизельные генераторы в наличии и под заказ.  От официального дилера."),
    "/catalog/dizelnye-generatory/filter/brand-transprogress/" => array("h1" => "дизель генераторы российского производства (Транспрогресс)", "title" => "Дизель генераторы российского производства  (Транспрогресс) купить", "keywords" => "Дизельные генераторы,  российского производства,  Транспрогресс, купить", "description" => "Дизель генераторы российского производства Транспрогресс - большой выбор. Дизельные генераторы Транспрогресс в наличии и под заказ в Москве, с доставкой в любой регион. "),
    "/catalog/generatory/filter/brand-transprogress/" => array("h1" => "Генераторы российского производства Транспрогресс (Transprogress)", "title" => "Генераторы российского производства Транспрогресс (Transprogress) купить", "keywords" => "Генераторы, российского производства, Транспрогресс (Transprogress)", "description" => "Генераторы российского производства Транспрогресс (Transprogress) от официального дилера."),
    "/catalog/generatory/filter/isposlenenie_generatory-kozhukhnyy/" => array("h1" => "Генераторы в кожухе", "title" => "Генераторы в кожухе купить", "keywords" => "Генераторы, в кожухе, купить", "description" => "Генераторы в кожухе от официального дилера"),
    "/catalog/generatory/filter/isposlenenie_generatory-otkrytyy/" => array("h1" => "Генераторы открытые", "title" => "Генераторы открытые купить", "keywords" => "Генераторы открытые, купить", "description" => "Генераторы открытые от официального дилера"),
    "/catalog/transportirovshchiki-pallet/filter/pto_tip_privoda-elektricheskiy/" => array("h1" => "Электрические тележки", "title" => "Электрические тележки", "keywords" => " электрические тележки, Электротележки, купить", "description" => "Электротележки (электрические тележки) - в наличии и под заказ."),
    
    "/catalog/vibroplity/filter/tip_mashiny-reversivnye_plity/" => array("h1" => "Виброплита реверсивная", "title" => "Виброплита реверсивная купить", "keywords" => " Виброплита , реверсивная, купить", "description" => "Виброплиты реверсивные - в наличии и под заказ. От официального дилера."),
    "/catalog/vibroplity/filter/tip_mashiny-pryamogo_khoda/" => array("h1" => "Виброплиты прямого хода", "title" => "Виброплиты прямого хода купить", "keywords" => " Виброплиты, прямого хода ,  купить", "description" => "Виброплиты прямого хода Амманн - в наличии и под заказ. От официального дилера."),
    
    "/catalog/bu-skladskaya-tehnika/bu_vilochnyy_pogruzchik_dizel/filter/city-moskva/" => array("h1" => "Погрузчик бу в Москве", "title" => "Погрузчик бу в Москве", "keywords" => "Вилочный погрузчик, дизельный, бу, Москва, купить", "description" => "Большой выбор БУ вилочных погрузчиков дизельных в Москве"),
    "/catalog/bu-skladskaya-tehnika/bu_vilochnyy_pogruzchik_benzin/filter/city-moskva/" => array("h1" => "Вилочный погрузчик бу купить в Москве", "title" => "Вилочный погрузчик бу купить в Москве", "keywords" => "Вилочный погрузчик, бензиновый,  бу, купить, Москва", "description" => "Вилочный погрузчик бензиновый бу купить в Москве"),
    "/catalog/bu-skladskaya-tehnika/bu_vilochnyy_pogruzchik_elektricheskiy/filter/brand-toyota/" => array("h1" => "Электропогрузчики TOYOTA бу", "title" => "Электропогрузчики TOYOTA купить бу", "keywords" => "Электропогрузчики, TOYOTA, бу", "description" => "Электропогрузчики TOYOTA бу"),
    "/catalog/bu-skladskaya-tehnika/bu_vilochnyy_pogruzchik_benzin/filter/brand-toyota/" => array("h1" => "Автопогрузчик TOYOTA бу", "title" => "Автопогрузчик TOYOTA бу купить", "keywords" => "Автопогрузчик, TOYOTA,  бу, купить", "description" => "Автопогрузчик TOYOTA  бу купить"),
    
	"/catalog/bu-stroitelnaya-tehnika/" => array("h1" => "Б у строительная техника", "title" => "Б у строительная техника", "keywords" => "б у строительная техника, строительная техника бу, продажа строительной техники бу", "description" => "На машины с предпродажной подготовкой предоставляется гарантия от 2-х до 6 месяцев, или от 200 до 600 моточасов, в зависимости от состояния техники."),
    
	//"description" => "На машины с предпродажной подготовкой предоставляется гарантия от 2-х до 6 месяцев, или от 200 до 600 моточасов, в зависимости от состояния техники.",
	//"keywords" => "б у строительная техника, строительная техника бу, продажа строительной техники бу",
	//"title" => "Б у строительная техника",
	//"keywords_inner" => "б у строительная техника, строительная техника бу, продажа строительной техники бу"
	
    "/catalog/kolesnye-krany/filter/tip_mashiny-korotkobaznyy/" => array("h1" => "Короткобазные краны", "title" => "Короткобазные краны купить", "keywords" => "Короткобазные краны, купить", "description" => "Короткобазные краны купить. Официальный дилер Grove в России."),
    "/catalog/kolesnye-krany/filter/tip_mashiny-samokhodnyy/" => array("h1" => "Стреловые самоходные краны", "title" => "Стреловые самоходные краны купить", "keywords" => "Стреловые, самоходные краны, купить", "description" => "Стреловые самоходные краны от официального дилера Grove в России."),
   
    
);





